version: '3.8'

services:
  # Chroma vector database
  chroma:
    image: chromadb/chroma:latest
    container_name: govchain-chroma
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_storage:/chroma/chroma
    environment:
      - CHROMA_SERVER_AUTHN_CREDENTIALS_FILE=/chroma/auth.txt
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.basic.BasicAuthenticationServerProvider
    networks:
      - govchain-network
    restart: unless-stopped

  # Vector search indexer (Node.js)
  indexer:
    build:
      context: ./indexer-node
      dockerfile: Dockerfile
    container_name: govchain-indexer
    ports:
      - "3000:3000"
    environment:
      - CHROMA_URL=http://chroma:8000
      - BLOCKCHAIN_API=http://host.docker.internal:1317
      - COLLECTION_NAME=govchain_datasets
      - PORT=3000
      - NODE_ENV=production
    depends_on:
      - chroma
    networks:
      - govchain-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Web interface
  web:
    image: nginx:alpine
    container_name: govchain-web
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    networks:
      - govchain-network
    restart: unless-stopped

networks:
  govchain-network:
    driver: bridge

volumes:
  chroma_storage:
